services:
  db:
    image: mariadb:11.4
    restart: unless-stopped
    environment:
      MARIADB_AUTO_UPGRADE: yes
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_USER: onmyshelf
      MARIADB_PASSWORD: onmyshelf
      MARIADB_DATABASE: onmyshelf
    volumes:
      - ./volumes/db/mysql:/var/lib/mysql

  redis:
    image: redis:7.4

  server:
    image: onmyshelf/server:${VERSION:-1.5.2}
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${HTTP_PORT:-8035}:80
    env_file: .env
    volumes:
      - ./volumes/backups:/var/backups/onmyshelf
      - ./volumes/logs:/var/log/onmyshelf
      - ./volumes/media:/var/www/html/media
      - ./volumes/api/modules:/var/www/html/api/v1/inc/modules
