services:
  db:
    image: mariadb:lts
    restart: unless-stopped
    environment:
      - MARIADB_AUTO_UPGRADE=yes
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_USER=onmyshelf
      - MARIADB_PASSWORD=onmyshelf
      - MARIADB_DATABASE=onmyshelf
    volumes:
      - ./volumes/db/mysql:/var/lib/mysql

  redis:
    image: redis:7.4

  server:
    image: onmyshelf/server:${VERSION:-1.5.0}
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${HTTP_PORT:-8035}:80
    environment:
      - OMS_URL
      - EMAIL_FROM
      - SMTP_SERVER
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASSWORD
      - LOGFILE
      - LOGGER_LEVEL
      - DEV_MODE
      - READ_ONLY
    volumes:
      - ./volumes/backups:/var/backups/onmyshelf
      - ./volumes/logs:/var/log/onmyshelf
      - ./volumes/media:/var/www/html/media
      - ./volumes/api/modules:/var/www/html/api/v1/inc/modules
