services:
  db:
    image: mariadb:11.8
    pull_policy: always
    restart: unless-stopped
    environment:
      MARIADB_AUTO_UPGRADE: true
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: onmyshelf
      MARIADB_PASSWORD: onmyshelf
      MARIADB_DATABASE: onmyshelf
    volumes:
      - ./volumes/db/mysql:/var/lib/mysql

  redis:
    image: redis:8.0
    pull_policy: always
    volumes:
      - ./volumes/redis:/data

  server:
    image: onmyshelf/server:${VERSION:-1.5.3}
    pull_policy: always
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${HTTP_PORT:-8035}:80
    env_file: .env
    volumes:
      - ./volumes/backups:/var/backups/onmyshelf
      - ./volumes/logs:/var/log/onmyshelf
      - ./volumes/media:/var/www/html/media
      - ./volumes/api/modules:/var/www/html/api/v1/inc/modules
