version: '3'
services:
  db:
    image: mariadb:10.8
    restart: unless-stopped
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_USER=onmyshelf
      - MARIADB_PASSWORD=onmyshelf
      - MARIADB_DATABASE=onmyshelf
    volumes:
      - ./volumes/db/mysql:/var/lib/mysql

  server:
    image: onmyshelf/server:${VERSION:-1.0.0}
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${HTTP_PORT:-8035}:80
    environment:
      - LOGFILE
      - LOGGER_LEVEL
      - DEV_MODE
      - READ_ONLY
    volumes:
      - ./volumes/backups:/var/backups/onmyshelf
      - ./volumes/logs:/var/log/onmyshelf
      - ./volumes/media:/var/www/html/media
      - ./volumes/api/modules:/var/www/html/api/v1/inc/modules
